name: Backend Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  deploy:
    name: Deploy Backend
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Backend
        run: echo "Deployment command for backend here (e.g., Render CLI, AWS CLI)"
