name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        run: npm run lint

      - name: Build Application
        run: npm run build

      - name: Cache Build Artifacts
        uses: actions/cache@v3
        with:
          path: build
          key: build-${{ github.sha }}

  test:
    name: Run Tests
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test -- --coverage

      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: coverage/

  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Deploy to Vercel
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "Deploying frontend to production"
            npm run deploy:production
          else
            echo "Deploying frontend to staging"
            npm run deploy:staging

  notify:
    name: Send Notifications
    runs-on: ubuntu-20.04
    needs: deploy
    steps:
      - name: Send Notification
        if: always()
        run: echo "Despliegue del frontend completado correctamente."
